server:
  port: 0
spring:
  application:
    name: customer-service
  datasource:
    url: jdbc:mysql://localhost:3306/ceo?serverTimezone=Asia/Seoul
    username: root
    password: "[dhqclwoa12]"
  jpa:
    hibernate:
      ddl-auto: none
    show-sql: true
eureka:
  instance:
    instanceId: ${spring.application.name}:${vcap.application.instance_id:${spring.application.instance_id:${random.value}}}
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka
